<?php

namespace App\Ai\Agents;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Ai\Contracts\Agent;
use Laravel\Ai\Contracts\HasStructuredOutput;
use Laravel\Ai\Promptable;
use Stringable;

/**
 * Extracts concrete, actionable tasks from a meeting transcript and Fireflies'
 * own action-item list. Titles are short and imperative, in English; a due date is
 * only inferred when the transcript clearly states one.
 */
class TaskExtractorAgent implements Agent, HasStructuredOutput
{
    use Promptable;

    /**
     * Get the instructions that the agent should follow.
     */
    public function instructions(): Stringable|string
    {
        return <<<'INSTRUCTIONS'
        You extract concrete, actionable tasks from a meeting transcript and the
        action items generated by Fireflies.

        Rules:
        - Only return real, actionable tasks. Skip general discussion points,
          opinions and decisions without an action.
        - Merge duplicate or overlapping tasks into one task.
        - Keep titles short and imperative, in English.
        - Only fill due_date (YYYY-MM-DD) when the transcript states a clear
          deadline relative to the meeting date. Otherwise leave it empty.
        - If there are no tasks, return an empty list.
        INSTRUCTIONS;
    }

    /**
     * Get the agent's structured output schema definition.
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            'tasks' => $schema->array()->items(
                $schema->object(fn ($schema) => [
                    'title' => $schema->string()->required(),
                    'description' => $schema->string()->nullable(),
                    'due_date' => $schema->string()->nullable(), // YYYY-MM-DD
                ])
            )->required(),
        ];
    }
}
